### ISSUE TITLE
Just FritzBox

### ISSUE THREAD

**Issue by ewoks** [thbe/docker-ntopng#1]
It is more a question than an issue, but I am not sure if this is FritzBox specific or one could use other routers like dummy Vodafone ConnectBox or more advanced pfSense as well. 

Thanks

**Comment by thbe** [comment]
It's not restricted to the FritzBox, it's more a capabilities question. The FritzBox has a mode that generates a pcap file on the fly which can be used by ntopng. So, if the Vodafone, pfsense, ... box can generate the same input it can be used as well. To get this up and running, the run.sh file need to be adjusted to pick up the right URL.
